# docker-compose.yml

services:
  flask-app:
    build: .
    ports:
      - "80:80"
    environment:
      - OLLAMA_API_URL=http://ollama:11434
      - MODEL_NAME=llama3.1:8b
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"

volumes:
  ollama-data:
