services:
  flask-app:
    build: .
    ports:
      - "80:80"
    environment:
      - OLLAMA_API_URL=http://ollama:11434
      - MODEL_NAME=llama3.1:8b
      - ALLOWED_MODELS=llama3.1:8b,deepseek-r1:1.5b
      - THINK_TAG_MODELS=deepseek-r1:1.5b
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    environment:
      - OLLAMA_KEEP_ALIVE=30m
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"

volumes:
  ollama-data: